from pathlib import Path

DEFAULT_DATA_PATH = Path("~/.elf64-context-hash").expanduser()
DEFAULT_OUTPUT_PATH = "output"
DEFAULT_REPO_ID = "rubenanko/binary-jepa"
DEFAULT_VOCAB_PATH = DEFAULT_DATA_PATH / Path("vocab.json")
DEFAULT_CHECKPOINT_PATH = DEFAULT_DATA_PATH / Path("latest.pt")
DEFAULT_VOCAB_SIZE = 371
DEFAULT_PREDICTOR_DIM = 256
PAD_TOKEN = "<PAD>"
UNKNOWN_TOKEN = "<UNK>"
MASK_TOKEN = "<MASK>"
ENCODED_PAD_TOKEN = 0
ENCODED_UNKNOWN_TOKEN = 1
ENCODED_MASK_TOKEN = 2
